### PR TITLE
DOC: addressing G3504558

### PR DESCRIPTION
**Pull request by mw-hrastega**

### CODE REVIEW

**Comment by mw-hrastega** [comment]
Borrowing some text from https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions

**Review by mcafaro — APPROVED** [review]
Looks good. Another idea to consider is just to put a filename above each example like this:

**.github/workflows/run-default-tasks.yml**
```yaml
name: Run Default Tasks in Build File
on: [push]
jobs:
  my-job:
    name: Run MATLAB Build
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Run build
        uses: matlab-actions/run-build@v2
```

**Comment by mw-hrastega** [comment]
> Looks good. Another idea to consider is just to put a filename above each example like this:
> 
> **.github/workflows/run-default-tasks.yml**
> 
> ```yaml
> name: Run Default Tasks in Build File
> on: [push]
> jobs:
>   my-job:
>     name: Run MATLAB Build
>     runs-on: self-hosted
>     steps:
>       - name: Check out repository
>         uses: actions/checkout@v4
>       - name: Run build
>         uses: matlab-actions/run-build@v2
> ```

Interesting idea. However, I think this approach takes us back to the issue we have in naming build folders in the MATLAB doc (that is, coming up with a different name for each example, adding -1/-2/-3, limiting the name to 3 words, ...)

**Comment by mcafaro** [comment]
They don't each have to have a unique name. The readme won't explode like example manager if two happen to have the same name :). They could all even be named something generic like "workflow.yml".

But it does clutter things up a little. So maybe we can see if just the paragraph is enough for now.

**Comment by mw-hrastega** [comment]
> They don't each have to have a unique name. The readme won't explode like example manager if two happen to have the same name :). They could all even be named something generic like "workflow.yml".
> 
> But it does clutter things up a little. So maybe we can see if just the paragraph is enough for now.

Haha. Yes, let's go ahead with the paragraph first :)

**Pull request merged**
